### PR TITLE
refactor/clean up

### PR DESCRIPTION
**Pull request by bvrockwell**
- writing to local dir or gcs rather than personal bucket
- adding launch script
- removing replicated scripts/code
- templating vertex-payload.json
- adding model checkpoint transfer in job launch
- adding debug param for appending sleep infinity to job launch

### CODE REVIEW

**Comment by hosseinsarshar** [comment]
Thanks for the PR:

Here is how to make a parameter required in a shell script:

`: "${GPUS_PER_NODE:?Must set GPUS_PER_NODE}"`

What we discussed:
- to add a launcher which does run the curl command in addition to making sure the required parameters are set properly
- parameterizing the script path so it could be changed by the user to covert fine-tuning, pretraining and .... with the same job.sh file.

**Comment by bvrockwell** [comment]
thinking through it, i'm going to have it passed as an argument to the launcher instead of requiring setting the environment variable ahead of time.

**Comment by bvrockwell** [comment]
@hosseinsarshar it looks like all the paths are no longer functional from the last PR being merged (the new structure doesn't look to be taken into account for all the nemo examples).

Do you see this as well?

**Comment by hosseinsarshar** [comment]
@bvrockwell regarding the non-functional paths - I got that, I have it fixed on my local branch - will push it once we have this PR closed.

**Comment by bvrockwell** [comment]
Ok i've added a launch script and configured vertex-payload.sh to be dynamic, this greatly reduces the code.

Updated the readme.

These are tested and work.

**Pull request merged**
